<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Filmju</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <ApplicationConfig Remove="Filmju.exe.config" />
    <ApplicationConfig Include="Filmju.exe.config" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic.PowerPacks.Vs">
      <HintPath>..\Microsoft.VisualBasic.PowerPacks.Vs.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>